### ISSUE TITLE
Remove the Kotlin Android Extensions Plugin

### ISSUE THREAD

**Issue by wangerekaharun** [wangerekaharun/GradleBuildPlugins#4]
Remove this Plugin from the Project as it will soon be deprecated.

**Comment by jumaallan** [comment]
Did you ever work on this? @wangerekaharun

**Comment by wangerekaharun** [comment]
> Did you ever work on this? @wangerekaharun

Not yet, have not had time to work on the issue.

**Comment by wangerekaharun** [comment]
Closed by #8
